
env:
    CIRRUS_SHELL: bash

task:
  name: "EvolutionX-Viva"
  timeout_in: 180m
  container:
      image: shazuxdubuntu/ubuntu:latest
      cpu: 8
      memory: 32G

  Sync_script:
      - curl -sL https://gist.github.com/RndwnZ/455d460ef22e331e8c7fca7e16971e06/build.sh | bash
