env:
    CIRRUS_SHELL: bash

task:
  name: "Miku"
  timeout_in: 180m
  container:
      image: shazuxdubuntu/ubuntu:latest
      cpu: 8
      memory: 32G

  Sync_script:
      - curl -sL hhttps://gist.githubusercontent.com/RndwnZ/8fe8f6f3f320c038c191d67e32280ea8/raw/eafa81bb9a6d8e37dbcbd8799d89808579e88071/build.sh | bash
