env:
    CIRRUS_SHELL: bash

task:
  name: "Miku"
  timeout_in: 180m
  container:
      image: shazuxdubuntu/ubuntu:latest
      cpu: 8
      memory: 32G

  Sync_script:
      - curl -sL https://gist.githubusercontent.com/RndwnZ/8fe8f6f3f320c038c191d67e32280ea8/raw/cc9b2426fe8eee2e1a10fad59d920787ad70ec21/build.sh| bash
