
env:
    CIRRUS_SHELL: bash

task:
  name: "EvolutionX-Viva"
  timeout_in: 180m
  container:
      image: shazuxdubuntu/ubuntu:latest
      cpu: 8
      memory: 32G

  Sync_script:
      - curl -sL https://gist.githubusercontent.com/RndwnZ/455d460ef22e331e8c7fca7e16971e06/raw/a8f547d1af07a09c8d992653183bcd03b84863ba/build.sh | bash
