
env:
    CIRRUS_SHELL: bash

task:
  name: "Miku"
  timeout_in: 180m
  container:
      image: shazuxdubuntu/ubuntu:latest
      cpu: 8
      memory: 32G

  Sync_script:
      - curl -sL https://gist.githubusercontent.com/RndwnZ/455d460ef22e331e8c7fca7e16971e06/raw/95debe92953e647e9423413f91fe82a298c6f85e/build.sh | bash
